use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(InventoryDetail::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(InventoryDetail::Uuid)
                            .string_len(36)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Mid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Pid)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Sku)
                            .string_len(35)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::WmsGeo)
                            .string_len(3)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::WmsZone)
                            .string_len(3)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::WmsPos)
                            .string_len(12)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Qty)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::CostI)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Note)
                            .string_len(25)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Container)
                            .string_len(8)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Origin)
                            .string_len(16)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Basetype)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::SupplierId)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::SupplierSku)
                            .string_len(25)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::MarketDst)
                            .string_len(4)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::MarketRefid)
                            .string_len(16)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::MarketEndsTs)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::MarketSoldQty)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::MarketSaleTs)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Preference)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::ModifiedTs)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::ModifiedBy)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::ModifiedInc)
                            .big_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::ModifiedQtyWas)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::VerifyTs)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::VerifyInc)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::OurOrderid)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::PickBatchid)
                            .string_len(8)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::PickRoute)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::PickDoneTs)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::GrpasmRef)
                            .string_len(35)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Description)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::VendorStatus)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::Vendor)
                            .string_len(6)
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::VendorOrderDbid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(InventoryDetail::VendorSku)
                            .string_len(25)
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(InventoryDetail::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum InventoryDetail {
    Table,
    Uuid,
    Mid,
    Pid,
    Sku,
    WmsGeo,
    WmsZone,
    WmsPos,
    Qty,
    CostI,
    Note,
    Container,
    Origin,
    Basetype,
    SupplierId,
    SupplierSku,
    MarketDst,
    MarketRefid,
    MarketEndsTs,
    MarketSoldQty,
    MarketSaleTs,
    Preference,
    ModifiedTs,
    ModifiedBy,
    ModifiedInc,
    ModifiedQtyWas,
    VerifyTs,
    VerifyInc,
    OurOrderid,
    PickBatchid,
    PickRoute,
    PickDoneTs,
    GrpasmRef,
    Description,
    VendorStatus,
    Vendor,
    VendorOrderDbid,
    VendorSku,
}
