use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Customers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Customers::Orgid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Mid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Username)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Prt)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Email)
                            .string_len(65)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Password)
                            .string_len(36)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Passhash)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Passsalt)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Firstname)
                            .string_len(50)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Lastname)
                            .string_len(50)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Phone)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::ModifiedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::LastloginGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::LastorderGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::OrderCount)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Newsletter)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::OptinGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::HintNum)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::HintAnswer)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::HintAttempts)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Ip)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Origin)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::Schedule)
                            .string_len(4)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::HasNotes)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::RewardBalance)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::IsAffiliate)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Customers::IsLocked)
                            .small_integer()
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Customers::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Customers {
    Table,
    Orgid,
    Mid,
    Username,
    Prt,
    Email,
    Password,
    Passhash,
    Passsalt,
    Firstname,
    Lastname,
    Phone,
    ModifiedGmt,
    LastloginGmt,
    LastorderGmt,
    OrderCount,
    Newsletter,
    OptinGmt,
    HintNum,
    HintAnswer,
    HintAttempts,
    Ip,
    Origin,
    Schedule,
    HasNotes,
    RewardBalance,
    IsAffiliate,
    IsLocked,
}
