use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Zusers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Zusers::Username)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Password)
                            .string_len(50)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::PasswordChanged)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(Zusers::Reseller)
                            .string_len(12)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::LastLogin)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(Zusers::Logins)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::CachedFlags)
                            .string_len(255)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Email)
                            .string_len(65)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Phone)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Salesperson)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::TechContact)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::OverduenotifyGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Ipaddr)
                            .string_len(16)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Data)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Sugarguid)
                            .string_len(65)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillDay)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillPackage)
                            .string_len(8)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillProvisioned)
                            .date()
                            .null()
                            .default("0000-00-00")
                    )
                    .col(
                        ColumnDef::new(Zusers::BillNextrun)
                            .date()
                            .null()
                            .default("0000-00-00")
                    )
                    .col(
                        ColumnDef::new(Zusers::BillLastexec)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(Zusers::BillOrderdate)
                            .timestamp()
                            .null()
                            .default("0000-00-00 00:00:00")
                    )
                    .col(
                        ColumnDef::new(Zusers::InvoiceCount)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillLockId)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillLockGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillCustomrates)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BillPricingRevision)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BppMember)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::PublishedFile)
                            .string_len(45)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::PublishedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BppReviewCount)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::Cluster)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::BsReturndays)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::TktsAvailable)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::TktsUsed)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::TktsLastusedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Zusers::IsNewbie)
                            .small_integer()
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Zusers::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Zusers {
    Table,
    Username,
    Password,
    PasswordChanged,
    Reseller,
    LastLogin,
    Logins,
    CachedFlags,
    Email,
    Phone,
    Salesperson,
    TechContact,
    OverduenotifyGmt,
    Ipaddr,
    Data,
    Sugarguid,
    BillDay,
    BillPackage,
    BillProvisioned,
    BillNextrun,
    BillLastexec,
    BillOrderdate,
    InvoiceCount,
    BillLockId,
    BillLockGmt,
    BillCustomrates,
    BillPricingRevision,
    BppMember,
    PublishedFile,
    PublishedGmt,
    BppReviewCount,
    Cluster,
    BsReturndays,
    TktsAvailable,
    TktsUsed,
    TktsLastusedGmt,
    IsNewbie,
}
