use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Products::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Products::Mid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Merchant)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Product)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Ts)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::ProductName)
                            .string_len(80)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Category)
                            .string_len(60)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Data)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Salesrank)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::LastsoldGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::BasePrice)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::BaseCost)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Supplier)
                            .string_len(6)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::SupplierId)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Mfg)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::MfgId)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Upc)
                            .string_len(15)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Options)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Profile)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::Mkt)
                            .big_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::ProdIs)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::MktBitstr)
                            .string_len(24)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Products::MkterrBitstr)
                            .string_len(16)
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Products::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Products {
    Table,
    Mid,
    Merchant,
    Product,
    Ts,
    ProductName,
    Category,
    Data,
    Salesrank,
    LastsoldGmt,
    BasePrice,
    BaseCost,
    Supplier,
    SupplierId,
    Mfg,
    MfgId,
    Upc,
    Options,
    Profile,
    Mkt,
    ProdIs,
    MktBitstr,
    MkterrBitstr,
}
