use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Orders::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Orders::Merchant)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Mid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Prt)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Orderid)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::BsSettlement)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::V)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::ModifiedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::PaidGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::PaidTxn)
                            .string_len(20)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::InvGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::ShippedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::SyncedGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Customer)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Pool)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderBillName)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderBillEmail)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderBillZone)
                            .string_len(12)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderBillPhone)
                            .string_len(12)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderShipName)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderShipZone)
                            .string_len(12)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::ReviewStatus)
                            .string_len(3)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderPaymentStatus)
                            .char_len(3)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderPaymentMethod)
                            .string_len(4)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderPaymentLookup)
                            .string_len(4)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderErefid)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::OrderTotal)
                            .string()
                            .not_null()
                            .default(0)
                    )
                    .col(
                        ColumnDef::new(Orders::OrderSpecial)
                            .string_len(40)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::ShipMethod)
                            .string_len(10)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Mkt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::MktBitstr)
                            .string_len(24)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Flags)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Items)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Yaml)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Cartid)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(Orders::Sdomain)
                            .text()
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Orders::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Orders {
    Table,
    Merchant,
    Mid,
    Prt,
    Orderid,
    BsSettlement,
    V,
    ModifiedGmt,
    PaidGmt,
    PaidTxn,
    InvGmt,
    ShippedGmt,
    SyncedGmt,
    Customer,
    Pool,
    OrderBillName,
    OrderBillEmail,
    OrderBillZone,
    OrderBillPhone,
    OrderShipName,
    OrderShipZone,
    ReviewStatus,
    OrderPaymentStatus,
    OrderPaymentMethod,
    OrderPaymentLookup,
    OrderErefid,
    OrderTotal,
    OrderSpecial,
    ShipMethod,
    Mkt,
    MktBitstr,
    Flags,
    Items,
    Yaml,
    Cartid,
    Sdomain,
}
