use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(SkuLookup::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SkuLookup::Mid)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Pid)
                            .string_len(30)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Invopts)
                            .string_len(15)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::GrpParent)
                            .string_len(35)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Sku)
                            .string_len(45)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Title)
                            .string_len(80)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Cost)
                            .string()
                            .not_null()
                            .default(0)
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Price)
                            .string()
                            .not_null()
                            .default(0)
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Upc)
                            .string_len(13)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Mfgid)
                            .string_len(25)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Supplierid)
                            .string_len(25)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Prodasm)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::Assembly)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvAvailable)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyOnshelf)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyOnorder)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyNeedship)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyMarkets)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyLegacy)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::QtyReserved)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzAsin)
                            .string_len(15)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsDone)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsTodo)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsSent)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsWait)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsWarn)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzFeedsError)
                            .small_integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzProductdbGmt)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::AmzError)
                            .text()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvOnShelf)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvOnOrder)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvIsBo)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvReorder)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::InvIsRsvp)
                            .integer()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::DssAgent)
                            .string_len(8)
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::DssRun)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::DssMood)
                            .string()
                            .null()
                    )
                    .col(
                        ColumnDef::new(SkuLookup::DssConfig)
                            .text()
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(SkuLookup::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum SkuLookup {
    Table,
    Mid,
    Pid,
    Invopts,
    GrpParent,
    Sku,
    Title,
    Cost,
    Price,
    Upc,
    Mfgid,
    Supplierid,
    Prodasm,
    Assembly,
    InvAvailable,
    QtyOnshelf,
    QtyOnorder,
    QtyNeedship,
    QtyMarkets,
    QtyLegacy,
    QtyReserved,
    AmzAsin,
    AmzFeedsDone,
    AmzFeedsTodo,
    AmzFeedsSent,
    AmzFeedsWait,
    AmzFeedsWarn,
    AmzFeedsError,
    AmzProductdbGmt,
    AmzError,
    InvOnShelf,
    InvOnOrder,
    InvIsBo,
    InvReorder,
    InvIsRsvp,
    DssAgent,
    DssRun,
    DssMood,
    DssConfig,
}
